# Generated by Django 5.0.4 on 2024-04-22 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0003_favoriteguideline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteGuideline',
            new_name='FavouriteGuideline',
        ),
    ]
