# Generated by Django 5.0.4 on 2024-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0005_alter_customguidelines_external_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customguidelines',
            name='medical_speciality',
            field=models.CharField(default='General', max_length=1024),
        ),
    ]
