# Generated by Django 5.0.4 on 2024-05-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0007_alter_trustguideline_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustguideline',
            name='locality',
            field=models.CharField(default='UHD', max_length=255),
        ),
        migrations.AddField(
            model_name='trustguideline',
            name='original_filename',
            field=models.CharField(default='null', max_length=1025),
        ),
    ]
