# Generated by Django 5.0.4 on 2024-05-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0008_trustguideline_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustguideline',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
