# Generated by Django 5.0.4 on 2024-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0009_trustguideline_viewcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustguideline',
            name='viewcount',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
