# Generated by Django 5.0.4 on 2024-05-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0010_alter_trustguideline_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustguideline',
            name='authors',
            field=models.CharField(default='null', max_length=1025),
        ),
        migrations.AddField(
            model_name='trustguideline',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustguideline',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trustguideline',
            name='version_number',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
