# Generated by Django 5.0.4 on 2024-05-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0012_alter_trustguideline_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustguideline',
            name='version_number',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
