# Generated by Django 5.0.4 on 2024-06-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0013_alter_trustguideline_version_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustguideline',
            name='authors',
            field=models.CharField(blank=True, max_length=1025, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='creation_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='review_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='version_number',
            field=models.CharField(db_index=True, default='0', max_length=255),
        ),
    ]
