# Generated by Django 5.0.4 on 2025-02-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0016_remove_trustguideline_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustguideline',
            name='last_updated_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
