# Generated by Django 5.0.4 on 2025-02-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableapp', '0017_trustguideline_last_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trustguideline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='medical_speciality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='original_filename',
            field=models.CharField(blank=True, max_length=1025, null=True),
        ),
        migrations.AlterField(
            model_name='trustguideline',
            name='version_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
